language: java

jdk:
  - oraclejdk8

services:
  - docker

addons:
  sonarqube: true

after_success:
  - ./gradlew jacocoTestReport coveralls
  - docker build -t sportchef/ping .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push sportchef/ping

env:
  global:
  - secure: dbzYdPfIG+uRqAopSAmFvgjk+zpEX5UeTG1yGjMbocSb6Yw03ZC7IljEPeKKAybcstrDA8zHVraCd4CacIBOrkKL/wS33T9UsAJtPAYg6jRAYuDEDUYKvYkT5/Je5mdkAEAu23KkGwKGGGsV71wmYiBsis7aAVjVXx5DRRYeguMuTdcWqvY1ACczI/RqFB/Cj2mgAfATwZkEJn6OG7spvq1ZbaEBdWtpL7VJ/uru5srxlc4tVn0ucNSQByP6Hamy0cmUo/N1ihEiRrdbV+RbHPbW5LtqH72FWeVWFNLmw3Py2ec6OdWQJ8K5fa/68XPb4dpO9CNgdPv159B7C4Zx/0FCbFbwpJa4pVue5qrlIZA+lUX48CrrCbQ4X+mf6LZICgJ+MhR/dHdzbl+ig7m2GyfYBC/Iva0+isIqPtLDWHjkz8Ebj6zECdK7atdsDRluNjfIT8R+zKBw/UVfhw687JOTWaGsSPihReNTsBxgqlb1dkpUIDgwlHdyrZWd/E/4N9NxhAwOqEj1oaxo7OudBgpHCajW7iWca1f9ET3pVkCwZO+WdI7OgtIt0gy1AZQjDKtOkmwGCrqxxdr1H8o/feg+Uz79tzcaGUQP8beCnvz3/7MODHtlq4m+yhjJqu1ydfKJDE+yeFumpSeOdcpYiH9pOkEyCnf0RT+xi9zyMTY=
  - secure: yOhk1X6zOuJWMJp9Q81VcnV6VtrC+QXThepp4v7duTyb/wo9LxNxi3n0u8dN8eHMzmxn3fA035mM2s8VjYFtE0tnTJLKEqADCm12nP5zWOg0YzHunf/GpuANNqZTF6uD8pyUsWSloixAWH9q+rh9geD3LwmCmcEejQWFWxm00EQFlLOqJ6S9XamB86nMQSPdcMVghojFaeFrTNaPcr/lkjBITI5kdy1Xv2ZAagoTQzq+ildvIzOM+12VHT2Pvj45MF1TTrx38wiX0aR4vAhthVAOTZipSadJvZB+rl/Ql5dSjQf2bFrRzv2A3XJW8t8UPk5zFRCWvC4WWYof4OAzifCpF+O/HkJJv2MGcRorTrlqPHPOzZKO6YtZaWXL9Kzu94TrGKHAKRCvUGwkAFsTC1XqagGW84wINc7wwXGHFe7l27wopEfgRSfGQTxckLOgxXhopIRtbiAFyRuUi5YXX4t0zSI88M+N3KAUY7TSIt4dAmyNU+m2HiavlxFUuZlmoE51X7GoSV0gQa+UpZv++HdII3SLNZtYgm+MA0uXsToproEpZslDLV9depRuuMf8VstCxPDdVnMCFgqx9wEfm+dLzm53pK61aVEc/a0Byjc1VczSgmnDlI1iRvt/OI5Qoar+dL4ytSXQSbhLi9d10Q2GG9mFoH/HTdTxNS9m+yw=
  - secure: H5CxGXFfGTzc5m56WgOnNHBnmRd3bIyVx94rYAhy+NDSo+RlBdc2c6BbvinHx4fVaQutSU1L01hAKtxRKe7bkwTP0c4ekKmprmMASUHCLoIz02cw/pVKrW14eApXUypc9bbAW0cEHGOBRNbFCRWfoHCimEetLcIavF2dsT/Cm+QAdYFl1RXNpYx3JHJbdlhVKcBex6BOFgNqDzOm0U6Vrm6t6yRKlaDiWMwR13e8IzX85rX9Jn7K9OUPmeWqodkutHQ6R1ZhVkHRRAwImuY+rbPknLDaqZ+EYArYGZYssKdruQmpOud3nTKgXnHF+PJItC0gZyn6thyxj1amupaLLlSZzwfYe8PAZIbAkqjH1I2tqzK7vrsVTOSozymTfyHBXyDDMVr1x/HNaeA2R5hfS53n8O+dOqokgiE8yNU49XuHWOuLN+mTxZuAe+hGNpYpAa8S8oYcF0v94Wx5p4Y480h3QLniLxbXnKTtADt2qvMyWVsRc0Ln64l3xufVbBqV9KiEA5N3lN+kcEnNHgmPyfsRpEFteVdfOnF6IaVlhKbfdMdr0uFFKfMfKFhRD6d8kvUsGiJwoTNyK6ykb5UDNJhUXBKfZ2ZmT3/0S9Wh3YVXLKG1nhqTXQ3yy5cu8ptHaHictHfIPVOlTV49ipb4Pv2c4scpJSR5gsEzre4MFpc=

script:
  - ./gradlew check
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
